// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAAaZVClNlMXgTktyjUg8lhLG5zSue4YY',
    appId: '1:69521612278:web:94878d39de047f667c7bd7',
    messagingSenderId: '69521612278',
    projectId: 'wizi-learn',
    authDomain: 'wizi-learn.firebaseapp.com',
    storageBucket: 'wizi-learn.firebasestorage.app',
    measurementId: 'G-01Y7WC8383',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAaZVClNlMXgTktyjUg8lhLG5zSue4YY',
    appId: '1:69521612278:web:94878d39de047f667c7bd7',
    messagingSenderId: '69521612278',
    projectId: 'wizi-learn',
    storageBucket: 'wizi-learn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAAaZVClNlMXgTktyjUg8lhLG5zSue4YY',
    appId: '1:69521612278:web:94878d39de047f667c7bd7',
    messagingSenderId: '69521612278',
    projectId: 'wizi-learn',
    storageBucket: 'wizi-learn.firebasestorage.app',
    iosClientId: '116888930892940117576',
    iosBundleId: 'com.wizi.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAAaZVClNlMXgTktyjUg8lhLG5zSue4YY',
    appId: '1:69521612278:web:94878d39de047f667c7bd7',
    messagingSenderId: '69521612278',
    projectId: 'wizi-learn',
    storageBucket: 'wizi-learn.firebasestorage.app',
    iosClientId: '116888930892940117576',
    iosBundleId: 'com.wizi.learn',
  );
} 